package constant;



public interface Constant {
      String[] PHONE_VIETTEL = new String[]{"032",
              "033",
              "034",
              "035",
              "036",
              "037",
              "038",
              "039",
              "086",
              "096",
              "097",
              "098"};

    String[] PHONE_VINAPHONE = new String[]{"081",
            "082",
            "083",
            "084",
            "085",
            "088",
            "091",
            "094"};

    String[] PHONE_MOBIEPHONE = new String[]{"089",
            "090",
            "093",
            "070",
            "079",
            "077",
            "076",
            "078"};

    String[] PLACE = new String[]{
            "An Giang",
            "Bà rịa – Vũng tàu",
            "Bắc Giang",
            "Bắc Kạn",
            "Bạc Liêu",
            "Bắc Ninh",
            "Bến Tre",
            "Bình Định",
            "Bình Dương",
            "Bình Phước",
            "Bình Thuận",
            "Cà Mau",
            "Cần Thơ",
            "Cao Bằng",
            "Đà Nẵng",
            "Đắk Lắk",
            "Đắk Nông",
            "Điện Biên",
            "Đồng Nai",
            "Đồng Tháp",
            "Gia Lai",
            "Hà Giang",
            "Hà Nam",
            "Hà Nội",
            "Hà Tĩnh",
            "Hải Dương",
            "Hải Phòng",
            "Hậu Giang",
            "Hòa Bình",
            "Hưng Yên",
            "Khánh Hòa",
            "Kiên Giang",
            "Kon Tum",
            "Lai Châu",
            "Lâm Đồng",
            "Lạng Sơn",
            "Lào Cai",
            "Long An",
            "Nam Định",
            "Nghệ An",
            "Ninh Bình",
            "Ninh Thuận",
            "Phú Thọ",
            "Phú Yên",
            "Quảng Bình",
            "Quảng Nam",
            "Quảng Ngãi",
            "Quảng Ninh",
            "Quảng Trị",
            "Sóc Trăng",
            "Sơn La",
            "Tây Ninh",
            "Thái Bình",
            "Thái Nguyên",
            "Thanh Hóa",
            "Thừa Thiên Huế",
            "Tiền Giang",
            "Thành phố Hồ Chí Minh",
            "Trà Vinh",
            "Tuyên Quang",
            "Vĩnh Long",
            "Vĩnh Phúc",
            "Yên Bái"
    };
    String[] FIRST_NAME = new String[]{
            "Nguyễn",
            "Trần",
            "Lê",
            "Phạm",
            "Huỳnh",
            "Hoàng",
            "Võ",
            "Vũ",
            "Phan",
            "Trương",
            "Bùi",
            "Đặng",
            "Đỗ",
            "Ngô",
            "Hồ",
            "Dương",
            "Đinh",
            "Đoàn",
            "Lâm",
            "Mai",
            "Trịnh",
            "Đào",
            "Cao",
            "Lý",
            "Hà",
            "Lưu",
            "Lương",
            "Thái",
            "Châu",
            "Tạ",
            "Phùng",
            "Tô",
            "Vương",
            "Văn",
            "Tăng",
            "Quách",
            "Lại",
            "Hứa"
    };

    String[] MIDDLE_NAME = new String[]{
            "thị",
            "văn",
            "bá",
            "khánh",
            "thùy",
            "hồng",
            "ngọc",
            "thu",
            "thùy",
            "tiến",
            "duy",
            "tuấn"
    };

    String[] LAST_NAME = new String[]{
            "hương",
            "anh",
            "phú",
            "ngọc",
            "tranG",
            "dung",
            "sơN",
            "vInh",
            "Hiếu",
            "tùnG",
            "trường",
            "tú",
            "hoàng",
            "phưƠng",
            "hùng",
            "đạt",
            "đồng",
            "thắng",
            "tiến"

    };


}
